// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyProductAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyDescriptionAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2020")>]
[<assembly: AssemblyVersionAttribute("1.4")>]
[<assembly: AssemblyFileVersionAttribute("1.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyProduct = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyDescription = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2020"
    let [<Literal>] AssemblyVersion = "1.4"
    let [<Literal>] AssemblyFileVersion = "1.4"
