// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("RaynMaker.Portfolio.WebUI")]
[assembly: AssemblyProduct("RaynMaker.Portfolio")]
[assembly: AssemblyDescription("RaynMaker.Portfolio")]
[assembly: AssemblyCopyright("Copyright @ 2021")]
[assembly: AssemblyVersion("1.4")]
[assembly: AssemblyFileVersion("1.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "RaynMaker.Portfolio.WebUI";
        internal const System.String AssemblyProduct = "RaynMaker.Portfolio";
        internal const System.String AssemblyDescription = "RaynMaker.Portfolio";
        internal const System.String AssemblyCopyright = "Copyright @ 2021";
        internal const System.String AssemblyVersion = "1.4";
        internal const System.String AssemblyFileVersion = "1.4";
    }
}
