// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RaynMaker.Portfolio.Specs")>]
[<assembly: AssemblyProductAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyDescriptionAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2018")>]
[<assembly: AssemblyVersionAttribute("1.2")>]
[<assembly: AssemblyFileVersionAttribute("1.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RaynMaker.Portfolio.Specs"
    let [<Literal>] AssemblyProduct = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyDescription = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2018"
    let [<Literal>] AssemblyVersion = "1.2"
    let [<Literal>] AssemblyFileVersion = "1.2"
