// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RaynMaker.Portfolio.Specs")>]
[<assembly: AssemblyProductAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyDescriptionAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2017")>]
[<assembly: AssemblyVersionAttribute("0.9")>]
[<assembly: AssemblyFileVersionAttribute("0.9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RaynMaker.Portfolio.Specs"
    let [<Literal>] AssemblyProduct = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyDescription = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2017"
    let [<Literal>] AssemblyVersion = "0.9"
    let [<Literal>] AssemblyFileVersion = "0.9"
