// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RaynMaker.Portfolio.Service")>]
[<assembly: AssemblyProductAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyDescriptionAttribute("RaynMaker.Portfolio")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2017")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RaynMaker.Portfolio.Service"
    let [<Literal>] AssemblyProduct = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyDescription = "RaynMaker.Portfolio"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2017"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
